config/routes.rb
Rails.application.routes.draw do
  resources :equipos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipo.rb
class Equipo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/equipos_controller.rb
class EquiposController < ApplicationController
  before_action :set_equipo, only: [:show, :edit, :update, :destroy]

  # GET /equipos
  # GET /equipos.json
  def index
    @equipos = Equipo.all
  end

  # GET /equipos/1
  # GET /equipos/1.json
  def show
  end

  # GET /equipos/new
  def new
    @equipo = Equipo.new
  end

  # GET /equipos/1/edit
  def edit
  end

  # POST /equipos
  # POST /equipos.json
  def create
    @equipo = Equipo.new(equipo_params)

    respond_to do |format|
      if @equipo.save
        format.html { redirect_to @equipo, notice: 'Equipo was successfully created.' }
        format.json { render :show, status: :created, location: @equipo }
      else
        format.html { render :new }
        format.json { render json: @equipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipos/1
  # PATCH/PUT /equipos/1.json
  def update
    respond_to do |format|
      if @equipo.update(equipo_params)
        format.html { redirect_to @equipo, notice: 'Equipo was successfully updated.' }
        format.json { render :show, status: :ok, location: @equipo }
      else
        format.html { render :edit }
        format.json { render json: @equipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipos/1
  # DELETE /equipos/1.json
  def destroy
    @equipo.destroy
    respond_to do |format|
      format.html { redirect_to equipos_url, notice: 'Equipo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipo
      @equipo = Equipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipo_params
      params.require(:equipo).permit(:nombrequi, :descripcion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/views/equipos/_form.html.erb
<%= form_for(equipo) do |f| %>
  <% if equipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(equipo.errors.count, "error") %> prohibited this equipo from being saved:</h2>

      <ul>
      <% equipo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombrequi %>
    <%= f.text_field :nombrequi %>
  </div>

  <div class="field">
    <%= f.label :descripcion %>
    <%= f.text_field :descripcion %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/equipos/edit.html.erb
<h1>Editing Equipo</h1>

<%= render 'form', equipo: @equipo %>

<%= link_to 'Show', @equipo %> |
<%= link_to 'Back', equipos_path %>

app/views/equipos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Equipos</h1>

<table id="equipos">
  <thead>
    <tr>
      <th>Nombrequi</th>
      <th>Descripcion</th>
      <th>Acciones</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @equipos.each do |equipo| %>
      <tr>
        <td><%= equipo.nombrequi %></td>
        <td><%= equipo.descripcion %></td>
        <td><%= link_to 'Show', equipo %>
            <%= link_to 'Edit', edit_equipo_path(equipo) %>
        <%= link_to 'Destroy', equipo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Equipo', new_equipo_path %>

app/views/equipos/new.html.erb
<h1>New Equipo</h1>

<%= render 'form', equipo: @equipo %>

<%= link_to 'Back', equipos_path %>

app/views/equipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombrequi:</strong>
  <%= @equipo.nombrequi %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @equipo.descripcion %>
</p>

<%= link_to 'Edit', edit_equipo_path(@equipo) %> |
<%= link_to 'Back', equipos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proycto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>